name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: |
          make -s setup

      - name: Linting
        run: |
          make -s auto_format
          make -s lint_test

      - name: Unit Tests
        run: |
          make -s unit_test

      - name: Security Scan
        run: |
          make -s security_scan

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: make setup

      - name: Build
        run: echo TO DO - make pypi package.
